"use client";

import { useState } from "react";
import AdminShell from "@/components/layout/AdminShell";
import { supabase } from "@/lib/supabase";
import { useAdmin } from "@/lib/useAdmin";
import {
  exportCandidatesToExcel,
  exportApprovedCandidates,
  exportVotersToExcel,
  exportPartiesToExcel,
  exportFinancialReport,
  exportFullRegister,
} from "@/lib/export";
import { Candidate, Voter, PoliticalParty } from "@/types";

interface ExportCard {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  action: () => Promise<void>;
}

export default function ExportCenterPage() {
  const { admin } = useAdmin();
  const [loading, setLoading] = useState<string | null>(null);
  const [lastExport, setLastExport] = useState<Record<string, string>>({});
  const [error, setError] = useState("");

  async function run(id: string, fn: () => Promise<void>) {
    setLoading(id);
    setError("");
    try {
      await fn();
      const now = new Date().toLocaleString("en-IN", {
        day: "2-digit", month: "short", year: "numeric",
        hour: "2-digit", minute: "2-digit",
      });
      setLastExport(p => ({ ...p, [id]: now }));

      // Log export to audit
      if (admin) {
        await supabase.from("audit_logs").insert([{
          actor_name: admin.full_name,
          actor_role: admin.role,
          action_type: "export",
          target_type: "system",
          target_id: id,
          description: `Excel export: "${id}" generated by ${admin.full_name}`,
        }]);
      }
    } catch (err) {
      console.error(err);
      setError("Export failed. Please try again.");
    } finally {
      setLoading(null);
    }
  }

  // ── DATA FETCHERS ──────────────────────────────────────
  async function fetchCandidates(): Promise<Candidate[]> {
    const { data } = await supabase.from("candidates").select("*").order("submitted_at", { ascending: false });
    return (data as Candidate[]) ?? [];
  }
  async function fetchVoters(): Promise<Voter[]> {
    const { data } = await supabase.rpc("rpc_voter_status_lookup", {
      passport_number: null,
      voter_id: null,
    });
    return (data as Voter[]) ?? [];
  }
  async function fetchParties(): Promise<PoliticalParty[]> {
    const { data } = await supabase.from("political_parties").select("*").order("submitted_at", { ascending: false });
    return (data as PoliticalParty[]) ?? [];
  }

  // ── EXPORT CARDS ───────────────────────────────────────
  const EXPORTS: ExportCard[] = [
    {
      id: "all-candidates",
      title: "All Candidates",
      description: "Complete candidate register — all statuses included. Every submission with full details.",
      icon: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z",
      color: "blue",
      action: async () => exportCandidatesToExcel(await fetchCandidates()),
    },
    {
      id: "approved-candidates",
      title: "Approved Candidates Only",
      description: "Official approved candidate list for ballot preparation and campaign clearance.",
      icon: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",
      color: "green",
      action: async () => exportApprovedCandidates(await fetchCandidates()),
    },
    {
      id: "voter-register",
      title: "Full Voter Register",
      description: "Complete voter list including verification status and ALSI membership details.",
      icon: "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2",
      color: "indigo",
      action: async () => exportVotersToExcel(await fetchVoters()),
    },
    {
      id: "approved-voters",
      title: "Approved Voters Only",
      description: "Final verified voter roll — only IEC-approved voters eligible to vote.",
      icon: "M5 13l4 4L19 7",
      color: "green",
      action: async () => {
        const voters = await fetchVoters();
        const approved = voters.filter(v => v.voter_approved);
        exportVotersToExcel(approved, "IEC_Approved_Voter_Roll");
      },
    },
    {
      id: "political-parties",
      title: "Political Parties Register",
      description: "All registered political parties with leadership, status and contact details.",
      icon: "M3 21v-4m0 0V5a2 2 0 012-2h6.5l1 1H21l-3 6 3 6h-8.5l-1-1H5a2 2 0 00-2 2zm9-13.5V9",
      color: "purple",
      action: async () => exportPartiesToExcel(await fetchParties()),
    },
    {
      id: "financial-report",
      title: "Financial Tracking Report",
      description: "Registration fee summary for all approved candidates. Total revenue calculation included.",
      icon: "M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
      color: "amber",
      action: async () => exportFinancialReport(await fetchCandidates()),
    },
    {
      id: "full-register",
      title: "Full Election Register",
      description: "Master export — all candidates, voters, and parties in one workbook with separate sheets.",
      icon: "M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4-8 4s8 1.79 8 4",
      color: "slate",
      action: async () => {
        const [c, v, p] = await Promise.all([fetchCandidates(), fetchVoters(), fetchParties()]);
        exportFullRegister(c, v, p);
      },
    },
  ];

  const colorMap: Record<string, { card: string; badge: string; btn: string; icon: string }> = {
    blue:   { card: "border-blue-200 bg-blue-50",     badge: "bg-blue-100 text-blue-700",    btn: "bg-blue-700 hover:bg-blue-800",     icon: "text-blue-600" },
    green:  { card: "border-green-200 bg-green-50",   badge: "bg-green-100 text-green-700",  btn: "bg-green-700 hover:bg-green-800",   icon: "text-green-600" },
    indigo: { card: "border-indigo-200 bg-indigo-50", badge: "bg-indigo-100 text-indigo-700",btn: "bg-indigo-700 hover:bg-indigo-800", icon: "text-indigo-600" },
    purple: { card: "border-purple-200 bg-purple-50", badge: "bg-purple-100 text-purple-700",btn: "bg-purple-700 hover:bg-purple-800", icon: "text-purple-600" },
    amber:  { card: "border-amber-200 bg-amber-50",   badge: "bg-amber-100 text-amber-700",  btn: "bg-amber-700 hover:bg-amber-800",   icon: "text-amber-600" },
    slate:  { card: "border-slate-200 bg-slate-50",   badge: "bg-slate-100 text-slate-700",  btn: "bg-[#0B1F3A] hover:bg-[#153E75]",  icon: "text-slate-600" },
  };

  return (
    <AdminShell>
      {/* HEADER */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-[#0B1F3A]">Export Center</h1>
        <p className="mt-1 text-sm text-slate-500">
          Generate official Excel reports from live election data. All exports are logged to the audit trail.
        </p>
      </div>

      {/* NOTICE */}
      <div className="mb-8 rounded-2xl border border-amber-200 bg-amber-50 p-5">
        <div className="flex gap-3">
          <svg className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <div>
            <p className="text-sm font-semibold text-amber-800">Official IEC Data Handling Notice</p>
            <p className="mt-1 text-sm text-amber-700">
              All exported files contain sensitive personal data of registered applicants.
              Handle in strict accordance with IEC data protection policy.
              Do not share with unauthorised parties. Every export is logged with your name and timestamp.
            </p>
          </div>
        </div>
      </div>

      {error && (
        <div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">
          {error}
        </div>
      )}

      {/* EXPORT GRID */}
      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        {EXPORTS.map(exp => {
          const c = colorMap[exp.color];
          const isLoading = loading === exp.id;
          const exported = lastExport[exp.id];

          return (
            <div key={exp.id} className={`flex flex-col rounded-2xl border p-6 shadow-sm ${c.card}`}>
              {/* ICON */}
              <div className={`mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-white shadow-sm`}>
                <svg className={`h-5 w-5 ${c.icon}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d={exp.icon} />
                </svg>
              </div>

              {/* CONTENT */}
              <div className="flex-1">
                <h3 className="text-base font-bold text-[#0B1F3A]">{exp.title}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-600">{exp.description}</p>
              </div>

              {/* LAST EXPORT */}
              {exported && (
                <div className="mt-4 flex items-center gap-2">
                  <svg className="h-3.5 w-3.5 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                  <p className="text-xs text-slate-500">Last exported: {exported}</p>
                </div>
              )}

              {/* BUTTON */}
              <button
                onClick={() => run(exp.id, exp.action)}
                disabled={!!loading}
                className={`mt-4 flex w-full items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold text-white transition disabled:cursor-not-allowed disabled:opacity-50 ${c.btn}`}
              >
                {isLoading ? (
                  <>
                    <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                    </svg>
                    Generating...
                  </>
                ) : (
                  <>
                    <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download .xlsx
                  </>
                )}
              </button>
            </div>
          );
        })}
      </div>

      {/* FORMAT NOTE */}
      <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <p className="text-sm font-semibold text-[#0B1F3A]">Export Format Details</p>
        <div className="mt-3 grid gap-3 text-sm text-slate-600 md:grid-cols-3">
          <div className="flex items-start gap-2">
            <span className="mt-0.5 rounded bg-green-100 px-1.5 py-0.5 text-xs font-bold text-green-700">.xlsx</span>
            <span>Microsoft Excel format — compatible with Google Sheets, LibreOffice, and all spreadsheet apps</span>
          </div>
          <div className="flex items-start gap-2">
            <span className="mt-0.5 rounded bg-blue-100 px-1.5 py-0.5 text-xs font-bold text-blue-700">LIVE</span>
            <span>Data is pulled directly from the database at export time — always reflects current state</span>
          </div>
          <div className="flex items-start gap-2">
            <span className="mt-0.5 rounded bg-slate-100 px-1.5 py-0.5 text-xs font-bold text-slate-700">LOG</span>
            <span>Every export is recorded in the audit log with your name, role, and timestamp</span>
          </div>
        </div>
      </div>
    </AdminShell>
  );
}